Associations
agneta1991/school_library pull request #5
Opened 2023-10-04 12:19 UTC by agneta1991

# Within this branch I have:
- Created a class Classroom with a @label variable
- Created a relationship between Classroom and Student classes
- Created a class Book with variables of @author and @title
- Created a Rental class with variable @date
- Created the many-to-many relationship between Person and Book using the intermediate class Rental

2023-10-04 15:04 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @agneta1991👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Good job with associations. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-04 15:04 UTC, thecodechaser commented on classroom.rb
> +  end
- [x] Please make sure the `students` variable is readable for the associations to work as expected.
  - You can consider using this. `attr_reader :students`.

2023-10-04 15:04 UTC, thecodechaser commented on classroom.rb
> +    @students = []
- [x] In the `students` class, Please make sure to add a  method that serves as the 'belongs-to' side (a student belongs to a classroom, both-ways-relationship).
- You can consider using the below code.

```ruby
 def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
```

2023-10-04 15:04 UTC, thecodechaser commented on classroom.rb
> +    @students = []
- [x] In the `students` class, Please make sure the `classroom` variable is readable for the associations to work as expected.
  - You can consider using this. `attr_reader :classroom`.

2023-10-04 15:04 UTC, thecodechaser commented on book.rb
> +  attr_reader :rentals
- [x] Please make sure the `rentals` variable is readable and writable for the associations to work as expected. You should add the `rentals` variable in the ` attr_accessor`.

2023-10-04 15:04 UTC, thecodechaser commented on person.rb
> +  attr_reader :id, :rentals
- [x] Please make sure the `rentals` variable is readable and writable for the associations to work as expected. You should add the `rentals` variable in the ` attr_accessor`.

2023-10-04 15:04 UTC, thecodechaser commented on rental.rb
> +  attr_reader :book, :person
- [ ] Please make sure the `book` and `person`  variables are also readable and writable for the associates to work as expected. You should add these variables in the ` attr_accessor`.

2023-10-05 08:32 UTC, agneta1991 commented
in the first submission of the project, the reviewer did not notice that i have forgot to write **require_relative** with file names with freshly created classes, could you be kind and double-check do i include those required files correctly, as i still struggle to understand some things, and i do not want to have some issues later in the project, thank you in advance 🙏

2023-10-05 08:46 UTC, MahmoudBakr23 approved these changes
Hi @agneta1991 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Highlights**
- Well done on making the required changes from the previous reviewer.

**Optional**
_Please see the comments under the review._

Cheers, and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-05 08:46 UTC, MahmoudBakr23 commented on book.rb
> +  attr_accessor :title, :author, :rentals
**Optional**
- Well done adding the requested changes as specified by the previous reviewer. However, it'd be more optimal if you moved these relations -in all of the classes- to the top of the class before the initializer, this is because when Ruby runs out of the program it could raise errors due to the time and order of the code execution, and we always want to ensure that Ruby knows the relationship between the classes first thing first. 👍

2023-10-05 09:14 UTC, agneta1991 commented on book.rb
> +  attr_accessor :title, :author, :rentals
@MahmoudBakr23 thank you so much for the suggestion, i will take all the tips 😄 , and then the comment i have left in regards of the **require_relative** , i am not sure have you seen it or not, is it all correct? Im so sorry for asking you all sorts, i just really want to understand and master ruby, but having some issues taking so much information at once 🙈

2023-10-05 09:19 UTC, MahmoudBakr23 commented on book.rb
> +  attr_accessor :title, :author, :rentals
@agneta1991 No problems ask all you want ☺️ Regarding the require relative, it is used when you want to inherit methods from one class to another but it has to be in the same directory aka code base that's why it's called require relative. In your situation it won't harm, as well as if you delete it.

2023-10-05 09:21 UTC, agneta1991 commented on book.rb
> +  attr_accessor :title, :author, :rentals
@MahmoudBakr23 thank you for a quick response 🙏 👍

2023-10-05 09:21 UTC, merged